default: &default
  adapter: postgresql
  host: localhost
  username: 'root'
  password: 123456
  timeout: 5000
  port: 5432
development:
  <<: *default
  database: app_development
test:
  <<: *default
  database: app_test
production:
  <<: *default
  database: app_production